# Configuración Prometheus para Portfolio Completo
# Monitoreo de todos los servicios del portfolio

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Solo servicios que tienen métricas expuestas
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Health checks básicos
  - job_name: 'health-checks'
    static_configs:
      - targets: 
          - 'api-proyecto1:8001'
          - 'api-nlp-proyecto3:8003'
          - 'api-recomendaciones-proyecto5:8005'
          - 'grafana:3000'
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 5s
